services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lostfound_db
      MYSQL_USER: lostfound_user
      MYSQL_PASSWORD: lostfound_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/gcp-key.json:/app/gcp-key.json
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data: