services:

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/gcp-key.json:/app/gcp-key.json

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
