version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: lostfound_mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lostfound_db
      MYSQL_USER: lostfound_user
      MYSQL_PASSWORD: lostfound_pass

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: